local h = require('tests.harness')
local bf = require('core.battlefield')

local CRATE = 0x1000300

h.check('option index decodes the high bits', function()
    h.eq(bf.option_index(0x140), 20)
    h.eq(bf.option_index(0), nil)
    h.eq(bf.option_index(255), nil)
end)

h.check('crate open then drops then grace produces full event with gil delta', function()
    local s = bf.new()
    bf.on_select(s, 146, 20, 'Beyond Infinity')
    bf.on_open(s, CRATE, 100, 5000, 146)
    h.eq(bf.on_drop(s, CRATE, 17316, 1, 101), true)
    h.eq(bf.on_drop(s, CRATE, 17316, 1, 101), true)
    h.eq(bf.on_drop(s, CRATE, 4096, 1, 102), true)
    h.eq(bf.on_drop(s, 999, 1, 1, 102), false)
    h.eq(bf.tick(s, 104, 17000), nil)
    local ev = bf.tick(s, 107, 17000)
    h.truthy(ev)
    h.eq(ev.type, 'battlefield')
    h.eq(ev.battlefield.name, 'Beyond Infinity')
    h.eq(ev.battlefield.entry_zone_id, 146)
    h.eq(ev.zone_id, 146)
    h.eq(ev.observed_at, 100)
    h.eq(#ev.items, 2)
    h.eq(ev.items[1].count, 2)
    h.eq(ev.gil, 12000)
    h.eq(ev.crate_actor_id, CRATE)
    h.eq(ev.partial, false)
    h.eq(bf.tick(s, 200, 17000), nil)
end)

h.check('no gil gives zero', function()
    local s = bf.new()
    bf.on_open(s, CRATE, 100, 5000, 146)
    local ev = bf.tick(s, 110, 5000)
    h.eq(ev.gil, 0)
end)

h.check('zoning mid crate emits partial', function()
    local s = bf.new()
    bf.on_select(s, 139, 3, 'Shooting Fish')
    bf.on_open(s, CRATE, 100, 0, 139)
    bf.on_drop(s, CRATE, 1, 1, 101)
    local ev = bf.on_zone(s, 300)
    h.eq(ev.partial, true)
    h.eq(#ev.items, 1)
    h.eq(ev.gil, 300)
    h.eq(bf.on_zone(s, 300), nil)
end)

h.check('unknown selection falls back to a zone placeholder name', function()
    local s = bf.new()
    bf.on_open(s, CRATE, 100, 0, 144)
    local ev = bf.tick(s, 110, 0)
    h.eq(ev.battlefield.name, 'unknown zone 144')
    h.eq(ev.battlefield.entry_zone_id, 144)
end)

h.check('reopening the same crate keeps the window', function()
    local s = bf.new()
    bf.on_open(s, CRATE, 100, 10, 1)
    bf.on_drop(s, CRATE, 7, 1, 101)
    bf.on_open(s, CRATE, 102, 10, 1)
    local ev = bf.tick(s, 110, 10)
    h.eq(#ev.items, 1)
end)
