local h = require('tests.harness')
local queue = require('core.queue')

local batch = { flush_seconds = 60, max_events = 3 }
local S = 'horizon'

local function ev(id, at, slug)
    return { id = id, observed_at = at, server_slug = slug }
end

h.check('empty queue never flushes', function()
    local q = queue.new()
    h.eq(queue.ready(q, 1000, batch, S), false)
end)

h.check('flushes when oldest event is flush_seconds old', function()
    local q = queue.new()
    queue.push(q, ev('a', 100))
    h.eq(queue.ready(q, 159, batch, S), false)
    h.eq(queue.ready(q, 160, batch, S), true)
end)

h.check('flushes when max_events reached', function()
    local q = queue.new()
    queue.push(q, ev('a', 100))
    queue.push(q, ev('b', 100))
    h.eq(queue.ready(q, 101, batch, S), false)
    queue.push(q, ev('c', 100))
    h.eq(queue.ready(q, 101, batch, S), true)
end)

h.check('events for another server do not count and are not sent', function()
    local q = queue.new()
    queue.push(q, ev('a', 0, 'phoenix'))
    queue.push(q, ev('b', 0, 'phoenix'))
    queue.push(q, ev('c', 0, 'phoenix'))
    h.eq(queue.ready(q, 1000, batch, S), false)
    queue.push(q, ev('d', 0, S))
    queue.push(q, ev('e', 0))
    h.eq(queue.ready(q, 100, batch, S), true)
    local b = queue.begin_batch(q, 10, S)
    h.eq(#b, 2)
    h.eq(b[1].id, 'd')
    h.eq(b[2].id, 'e')
    queue.finish_ok(q)
    h.eq(queue.depth(q), 3)
end)

h.check('begin_batch takes oldest events and blocks a second flush', function()
    local q = queue.new()
    for i = 1, 5 do queue.push(q, ev('e' .. i, i)) end
    local b = queue.begin_batch(q, 3, S)
    h.eq(#b, 3)
    h.eq(b[1].id, 'e1')
    h.eq(queue.ready(q, 1000, batch, S), false)
    h.eq(queue.finish_ok(q), 3)
    h.eq(queue.depth(q), 2)
    h.eq(q.events[1].id, 'e4')
end)

h.check('drop_indexes removes only the named in-flight events', function()
    local q = queue.new()
    for i = 1, 4 do queue.push(q, ev('e' .. i, 0)) end
    queue.begin_batch(q, 3, S)
    h.eq(queue.drop_indexes(q, { 0, 2, 9 }), 2)
    h.eq(queue.depth(q), 2)
    h.eq(q.events[1].id, 'e2')
    h.eq(q.events[2].id, 'e4')
    h.eq(q.in_flight, nil)
end)

h.check('retry backs off exponentially and caps at 15 minutes', function()
    local q = queue.new()
    queue.push(q, ev('a', 0))
    queue.begin_batch(q, 10, S)
    h.eq(queue.finish_retry(q, 1000), 30)
    h.eq(queue.ready(q, 1029, batch, S), false)
    h.eq(queue.ready(q, 1030, batch, S), true)
    queue.begin_batch(q, 10, S)
    h.eq(queue.finish_retry(q, 2000), 60)
    queue.begin_batch(q, 10, S)
    h.eq(queue.finish_retry(q, 3000), 120)
    for _ = 1, 10 do
        queue.begin_batch(q, 10, S)
        queue.finish_retry(q, 4000)
    end
    h.eq(q.next_attempt_at - 4000, 900)
    h.eq(queue.depth(q), 1)
end)

h.check('retry_after overrides the backoff schedule', function()
    local q = queue.new()
    queue.push(q, ev('a', 0))
    queue.begin_batch(q, 10, S)
    h.eq(queue.finish_retry(q, 100, 600), 600)
    h.eq(q.next_attempt_at, 700)
end)

h.check('success resets the backoff', function()
    local q = queue.new()
    queue.push(q, ev('a', 0))
    queue.begin_batch(q, 10, S)
    queue.finish_retry(q, 100)
    queue.begin_batch(q, 10, S)
    queue.finish_ok(q)
    h.eq(q.attempts, 0)
    queue.push(q, ev('b', 0))
    queue.begin_batch(q, 10, S)
    h.eq(queue.finish_retry(q, 200), 30)
end)

h.check('halt keeps events and blocks flushing until resume', function()
    local q = queue.new()
    queue.push(q, ev('a', 0))
    queue.begin_batch(q, 10, S)
    queue.finish_halt(q, 'auth')
    h.eq(queue.depth(q), 1)
    h.eq(queue.ready(q, 10000, batch, S), false)
    queue.resume(q)
    h.eq(queue.ready(q, 10000, batch, S), true)
end)

h.check('drop_batch removes only the in-flight events', function()
    local q = queue.new()
    for i = 1, 4 do queue.push(q, ev('e' .. i, 0)) end
    queue.begin_batch(q, 2, S)
    h.eq(queue.drop_batch(q), 2)
    h.eq(queue.depth(q), 2)
    h.eq(q.events[1].id, 'e3')
end)

h.check('drop_server removes that server and unlabelled events only', function()
    local q = queue.new()
    queue.push(q, ev('a', 0, S))
    queue.push(q, ev('b', 0))
    queue.push(q, ev('c', 0, 'phoenix'))
    h.eq(queue.drop_server(q, S), 2)
    h.eq(queue.depth(q), 1)
    h.eq(q.events[1].id, 'c')
end)

h.check('cap drops oldest first and warns once', function()
    local q = queue.new()
    local old_cap = queue.DISK_CAP
    queue.DISK_CAP = 3
    for i = 1, 3 do queue.push(q, ev('e' .. i, i)) end
    local dropped, warn = queue.push(q, ev('e4', 4))
    h.eq(dropped, 1)
    h.eq(warn, true)
    h.eq(q.events[1].id, 'e2')
    dropped, warn = queue.push(q, ev('e5', 5))
    h.eq(dropped, 1)
    h.eq(warn, false)
    queue.DISK_CAP = old_cap
end)

h.check('export and import round trip keeps observation times', function()
    local q = queue.new()
    queue.push(q, ev('a', 10))
    queue.push(q, ev('b', 20, S))
    local data = queue.export(q)
    local q2 = queue.new()
    h.eq(queue.import(q2, data), 2)
    h.eq(q2.events[2].observed_at, 20)
    h.eq(q2.events[2].server_slug, S)
    h.eq(queue.import(q2, { events = { { bogus = true } } }), 0)
    h.eq(queue.import(q2, 'junk'), 0)
end)
