"""Generate data/battlefields.lua from a LandSandBoat checkout.

Usage: python tools/gen_battlefields.py <path to a LandSandBoat checkout>
"""
import os
import re
import sys


def load_zones(root):
    path = os.path.join(root, "scripts", "enum", "zone.codegen.lua")
    zones = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"\s*([A-Z0-9_]+)\s*=\s*(\d+)", line)
            if m:
                zones[m.group(1)] = int(m.group(2))
    return zones


def parse_battlefield(path):
    name = None
    zone = None
    index = None
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    for line in lines[:4]:
        m = re.match(r"^--\s+(.+?)\s*$", line)
        if m and not name and not line.startswith("----"):
            name = m.group(1)
    for line in lines:
        m = re.search(r"zoneId\s*=\s*xi\.zone\.([A-Z0-9_]+)", line)
        if m:
            zone = m.group(1)
        m = re.search(r"^\s*index\s*=\s*(\d+)", line)
        if m:
            index = int(m.group(1))
    return name, zone, index


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(2)
    root = sys.argv[1]
    zones = load_zones(root)
    table = {}
    base = os.path.join(root, "scripts", "battlefields")
    for zone_dir in sorted(os.listdir(base)):
        d = os.path.join(base, zone_dir)
        if not os.path.isdir(d):
            continue
        for fn in sorted(os.listdir(d)):
            if not fn.endswith(".lua"):
                continue
            name, zone, index = parse_battlefield(os.path.join(d, fn))
            if name is None or zone is None or index is None or zone not in zones:
                print("skip", zone_dir, fn, name, zone, index, file=sys.stderr)
                continue
            table.setdefault(zones[zone], {})[index] = name
    out_path = os.path.join(os.path.dirname(__file__), "..", "data", "battlefields.lua")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="ascii", newline="\n") as out:
        out.write("-- Generated by tools/gen_battlefields.py; do not edit by hand.\n")
        out.write("-- Keyed by zone id, then by battlefield menu index.\n")
        out.write("return {\n")
        for zone_id in sorted(table):
            out.write("    [%d] = {\n" % zone_id)
            for index in sorted(table[zone_id]):
                escaped = table[zone_id][index].replace("\\", "\\\\").replace("'", "\\'")
                out.write("        [%d] = '%s',\n" % (index, escaped))
            out.write("    },\n")
        out.write("}\n")
    total = sum(len(v) for v in table.values())
    print("wrote %d battlefields across %d zones" % (total, len(table)))


if __name__ == "__main__":
    main()
